swagger: "2.0"
info:
  version: 1.0.0
  title: firestone-server
  description: firestone-server
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
  - name: Users
    description: system user information
  - name: ConfigMocks
    description: mock trade configuration
  - name: MockTrades
    description: mock trade records

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  UserBody:
    type: object
    title: user
    required:
      - username
      - password
    properties:
      username:
        type: string
        example: aqua
      password:
        type: string
        example: '123456'  
  configMockBody:
    type: object
    title: ConfigMock
    required:
      - accesstoken
      - update
    properties:
      accesstoken:
        type: string
        example: NWQ5MDVkYjlmYzg0ZDMyMjRiMGViNTljOjE2Nzg0M2Q5ZDQ3ZGJlMGE2OWE4MWEzYjBjNDgwNmY1NDM5NmM5ZmY5YjU4OWExNTdkMTE3Y2FjOWQzYmMzMGU=
      update:
        type: object
        example: {
          maxBuyNum : 4        
        } 
  mockTradeBody:
    type: object
    title: MockTrade
    required:
      - accesstoken
      - update
    properties:
      accesstoken:
        type: string
        example: NWQ5MDVkYjlmYzg0ZDMyMjRiMGViNTljOjE2Nzg0M2Q5ZDQ3ZGJlMGE2OWE4MWEzYjBjNDgwNmY1NDM5NmM5ZmY5YjU4OWExNTdkMTE3Y2FjOWQzYmMzMGU=
      mocktradeid:
        type: string
        example: 5da1800e87b64fb6f4c32503
      update:
        type: object
        example: {
          deleted : true,
          state: '启动',
          result: '以19.24买入400股'
        }
              

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /users/login:
    post:
      tags:
        - Users
      description: login system 
      parameters:
        - name: user
          in: body
          required: true
          description: The login info
          schema: 
            $ref: "#/definitions/UserBody"
      responses:
        200:
          description: Return the login result
  
  /users/auth:
    get:
      tags:
        - Users
      description: auth user
      parameters:
        - name: accesstoken
          in: header
          required: true
          description: The auth info
          type: string
      responses:
        200:
          description: Return the auth result  

  /configmock/{accesstoken}:
    get:
      tags:
        - ConfigMocks
      description: get user mock trade config
      parameters:
        - name: accesstoken
          in: path
          required: true
          x-example: NWQ5MDVkYjlmYzg0ZDMyMjRiMGViNTljOjE2Nzg0M2Q5ZDQ3ZGJlMGE2OWE4MWEzYjBjNDgwNmY1NDM5NmM5ZmY5YjU4OWExNTdkMTE3Y2FjOWQzYmMzMGU=
          description: The accesstoken of the ConfigMock to retrieve
          type: string
      responses:
        200:
          description: Return the ConfigMock with the specified accesstoken

  /configmock:
    post:
      tags:
        - ConfigMocks
      description: save user mock trade config
      parameters:
        - name: postData
          in: body
          required: true
          description: The postData of the ConfigMock
          schema: 
            $ref: "#/definitions/configMockBody"
      responses:
        200:
          description: Return the updated new ConfigMock

  /mocktrade/{accesstoken}:
    get:
      tags:
        - MockTrades
      description: get mock trade datas
      parameters:
        - name: accesstoken
          in: path
          required: true
          description: the user accesstoken
          x-example: NWQ5MDVkYjlmYzg0ZDMyMjRiMGViNTljOjE2Nzg0M2Q5ZDQ3ZGJlMGE2OWE4MWEzYjBjNDgwNmY1NDM5NmM5ZmY5YjU4OWExNTdkMTE3Y2FjOWQzYmMzMGU=
          type: string
      responses:
        200:
          description: Return the user mock trade records 
  
  /mocktrade:
    post:
      tags:
        - MockTrades  
      description: update mock trade 
      parameters:
        - name: postData 
          in: body
          required: true
          description: the mocktrade update data
          schema: 
            $ref: "#/definitions/mockTradeBody"
      responses:
        200:
          description: Return the updated mock trade      

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification