swagger: "2.0"
info:
  version: 1.0.0
  title: firestone-server
  description: firestone-server
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
  - name: Users
    description: system user information

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  UserBody:
    type: object
    title: user
    required:
      - username
      - password
    properties:
      username:
        type: string
        example: aqua
      password:
        type: string
        example: '123456'  

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /users/login:
    post:
      tags:
        - Users
      description: login system 
      parameters:
        - name: user
          in: body
          required: true
          description: The login info
          schema: 
            $ref: "#/definitions/UserBody"
      responses:
        200:
          description: Return the login result
  
  /users/auth:
    get:
      tags:
        - Users
      description: auth user
      parameters:
        - name: accesstoken
          in: header
          required: true
          description: The auth info
          type: string
      responses:
        200:
          description: Return the auth result  

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification